
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, we explore the impact of central clearing on derivative contracts, specifically contrasting Exchange-Traded Derivatives (ETDs) like futures with Over-The-Counter (OTC) derivatives like forwards. The application aims to provide a practical tool for risk managers, compliance officers, and institutional finance students to understand how margin requirements and daily settlement reduce cash flow and price differences between these contract types.
""")

page = st.sidebar.selectbox(label="Navigation", options=["Introduction & Spot Price", "Cash Flow Simulation", "Risk Analysis & Heatmap"])

if page == "Introduction & Spot Price":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Cash Flow Simulation":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "Risk Analysis & Heatmap":
    from application_pages.page3 import run_page3
    run_page3()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
