
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, we will explore the impact of central clearing on derivatives markets, specifically focusing on how margin requirements and daily settlement for centrally cleared OTC contracts reduce the cash flow and price differences between ETDs like futures and OTC forwards.
This application allows you to simulate different market conditions and clearing scenarios to visualize these effects.
""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Central Clearing Impact Simulator"])
if page == "Central Clearing Impact Simulator":
    from application_pages.central_clearing_simulator import run_central_clearing_simulator
    run_central_clearing_simulator()
# Your code ends
st.divider()
st.write("© 2025 QuantUniversity. All Rights Reserved.")
st.caption("The purpose of this demonstration is solely for educational use and illustration. "
            "Any reproduction of this demonstration "
            "requires prior written consent from QuantUniversity. "
            "This lab was generated using the QuCreate platform. QuCreate relies on AI models for generating code, which may contain inaccuracies or errors")


# License
st.markdown('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
