
import streamlit as st

def run_references():
    st.header("References")
    st.markdown("""
    [1] "REFRESHER READING 2024 CFA® PROGRAM LEVEL 1 Derivatives: Pricing and Valuation of Futures Contracts", CFA Institute, 2023. This document explains the impact of central clearing on OTC derivatives and how it affects the differences between futures and forward contracts, including the role of margin requirements.
    """)
    st.markdown("---")
    st.markdown("## QuantUniversity License")
    st.markdown("""
    © QuantUniversity 2025
    This notebook was created for **educational purposes only** and is **not intended for commercial use**.
    - You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.
    - You **may not delete or modify this license cell** without authorization.
    - This notebook was generated using **QuCreate**, an AI-powered assistant.
    - Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.

    All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
    """)
